modLoader="javafml"
loaderVersion="[41,)"
license="GPL3"

[[mods]]
modId="redundantguns"
version="1.0.99"
displayName="Redundant Guns (Dev. Branch)"
updateJSONURL=""
displayURL=""
logoFile="nzgexpansion_banner.png"
authors="zaeonNineZero"
description='''
An addon to NineZero's Gun Expansion, adding even more guns that would be too out-of-place or redundant in the main mod.)
'''

[[dependencies.redundantguns]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.redundantguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.redundantguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.3.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.redundantguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.redundantguns]]
    modId="nzgmaddon"
    mandatory=true
    versionRange="[1.4.4,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.redundantguns]
    catalogueImageIcon="nzgexpansion_icon.png"
